[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version"

[build]
  publish = ".next"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
